### ISSUE TITLE
bug: settings for ALB and ECS in template files are overwritten by tflocal/LocalStack on deploy

### ISSUE THREAD

**Issue by mciver-pk** [localstack/terraform-local#56] opened 2024-05-02 21:56 UTC
when we deploy our ALB and ECS cluster+service to a fresh LocalStack instance everything works correctly. however, on subsequent uses of `tflocal apply|plan [...]`, instead of returning the expected "No changes. Your infrastructure matches the configuration. [...] Apply complete! Resources: 0 added, 0 changed, 0 destroyed", we are instead warned of updates to our resources despite no changes to our TF template files. it seems as though on the initial deploy LocalStack changes the ALB listener's port to 4566, changes the `deployment_maximum_percent value` and`deployment_minimum_healthy_percent` values of my service from 100 to 200 and 50 to 100 respectively, plus a few other things. after running the apply, access to the service is broken and the stack needs to be torn down and reset.

i've attached an archive with a set of example template files that reproduce this (this doesn't deploy an application, but the changes when planning/applying are evident). steps to reproduce:
1. LS_DEBUG=trace localstack start -d
2. unzip Archive.zip, cd to it
3. terraform init
4. tflocal apply
5. tflocal apply/plan
6. observe attempt to change port from 4566 to port specified in template file, probably among other things

localstack version 3.2.0
docker version 26.0.0
macos version ventura 13.4.1

unsure if this is an issue with terraform-local or LocalStack. if this is expected behavior, there is no clear documentation i've seen on how to expect / account for this behavior. at the moment we are unable to re-deploy a stack without completely tearing down the infra and LocalStack instance. 

[archive.zip](https://github.com/localstack/terraform-local/files/15194430/Archive.zip)

**Comment by mciver-pk** [comment] 2024-05-02 22:56
i also notice this in the LocalStack container logs - 
```
2024-05-02 15:51:31 2024-05-02T22:51:31.346  INFO --- [164 (worker)] l.s.e.t.docker             : Stopping Docker container ls-ecs-REDACTED_cluster-localstack-ae2e9117-414d-4c25-8b1f-b5ece6794006-0-7c22bd85 for ECS task arn:aws:ecs:us-east-1:000000000000:task/REDACTED_cluster-localstack/ae2e9117-414d-4c25-8b1f-b5ece6794006
2024-05-02 15:51:41 2024-05-02T22:51:41.682  WARN --- [   asgi_gw_2] l.aws.protocol.serializer  : Response object TaskSet contains a member which is not specified: regionName
2024-05-02 15:51:41 2024-05-02T22:51:41.683  WARN --- [   asgi_gw_2] l.aws.protocol.serializer  : Response object TaskSet contains a member which is not specified: clientToken
2024-05-02 15:51:41 2024-05-02T22:51:41.698  WARN --- [   asgi_gw_0] l.aws.protocol.serializer  : Response object Service contains a member which is not specified: clusterName
2024-05-02 15:51:41 2024-05-02T22:51:41.699  WARN --- [   asgi_gw_0] l.aws.protocol.serializer  : Response object Service contains a member which is not specified: regionName
2024-05-02 15:51:41 2024-05-02T22:51:41.699  WARN --- [   asgi_gw_0] l.aws.protocol.serializer  : Response object Service contains a member which is not specified: enableEcsManagedTags
2024-05-02 15:51:41 2024-05-02T22:51:41.699  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS ecs.UpdateService => 200
```

now starting to believe the ECS cluster breaking is some issue with setting a new task or something... would still want clarification on the port stuff too. this all works correctly in AWS as well

**Comment by lakkeger** [comment] 2024-05-03 15:53
Hi @mciver-pk,
Thank you for reporting this issue and providing a working sample. I can confirm that the report is valid, however this seems to be a Localstack problem rather tflocal. So I close this ticket here and forward your findings to the team.

Unfortunately our implementation is not perfect yet, however our engineers working tirelessly on the improvement. As I know, the roadmap had been laid out for these services (ECS, ALB) so you can expect improvements in near future versions, until that I'd like to ask your patience.

If you have further questions please do not hesitate to reach out.

**Closed by lakkeger** 2024-05-03 15:53 UTC
