### ISSUE TITLE
connection refused when creating a bucket

### ISSUE THREAD

**Issue by evbo** [localstack/terraform-local#12] opened 2023-03-21 00:57 UTC
I am trying to create the following bucket in localstack, which is running in docker-compose as a service called `localstack`:

```
resource "aws_s3_bucket" "bucket" {
  bucket = "my-bucket-test"
}
```

If I use tflocal it fails with:
> │ Error: creating Amazon S3 (Simple Storage) Bucket (my-bucket-test): RequestError: send request failed
│ caused by: Put "http://my-bucket-test.s3.localhost.localstack.cloud:4566/": dial tcp 127.0.0.1:4566: connect: connection refused
│ 
│   with module.lambda.aws_s3_bucket.bucket,
│   on ../../../modules/aws-lambda/main.tf line 58, in resource "aws_s3_bucket" "bucket":
│   58: resource "aws_s3_bucket" "bucket" {
│ 
╵

If I use awslocal it fails with:
> awslocal   s3 mb s3://my-bucket2 
make_bucket failed: s3://my-bucket2 Could not connect to the endpoint URL: "http://localhost:4566/my-bucket2"

If I use aws it succeeds:
> AWS_PAGER="" AWS_ACCESS_KEY_ID=none AWS_SECRET_ACCESS_KEY=none aws   --endpoint-url http://localstack:4566   s3 mb s3://my-bucket2
make_bucket: my-bucket2

It seems credentials are not being correctly overidden?

Version:
> tflocal -version
Terraform v1.4.2
on linux_arm64
> + provider registry.terraform.io/hashicorp/archive v2.3.0
> + provider registry.terraform.io/hashicorp/aws v4.59.0

System:
> uname -a
Linux 963e1c10f21e 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

**Comment by evbo** [comment] 2023-03-21 14:51
Here are debug logs when trying to perform apply:
> caused by: Put "http://my-bucket-test.s3.localhost.localstack.cloud:4566/": dial tcp 127.0.0.1:4566: connect: connection refused" timestamp=2023-03-21T14:19:09.277Z
2023-03-21T14:19:09.278Z [ERROR] provider.terraform-provider-aws_v4.59.0_x5: Response contains error diagnostic: diagnostic_detail= tf_provider_addr=registry.terraform.io/hashicorp/aws tf_req_id=bd4fed47-7630-42aa-7a09-a89896e601f2 tf_resource_type=aws_s3_bucket @module=sdk.proto diagnostic_severity=ERROR diagnostic_summary="creating Amazon S3 (Simple Storage) Bucket (my-bucket-test): RequestError: send request failed
caused by: Put "http://my-bucket-test.s3.localhost.localstack.cloud:4566/": dial tcp 127.0.0.1:4566: connect: connection refused" tf_proto_version=5.3 tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 timestamp=2023-03-21T14:19:09.277Z
2023-03-21T14:19:09.282Z [ERROR] vertex "module.lambda.aws_s3_bucket.bucket" error: creating Amazon S3 (Simple Storage) Bucket (my-bucket-test): RequestError: send request failed
caused by: Put "http://my-bucket-test.s3.localhost.localstack.cloud:4566/": dial tcp 127.0.0.1:4566: connect: connection refused
2023-03-21T14:19:13.111Z [DEBUG] provider.terraform-provider-aws_v4.59.0_x5: HTTP Request Sent: tf_resource_type=aws_lambda_function aws.service=Lambda net.peer.port=4566 tf_req_id=1bb1f7ca-af56-4c27-c2d4-13ab085ab538 @module=aws aws.custom_endpoint_source=true aws.sdk=aws-sdk-go-v2 http.request.header.amz_sdk_invocation_id=580395eb-059f-4487-bcaa-7cb7fda4a171 http.request.header.amz_sdk_request="attempt=1; max=25" @caller=github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.24/logging/logger.go:39 aws.region=us-west-1 http.method=GET net.peer.name=localstack http.url=http://localstack:4566/2015-03-31/functions/fetch_ms_stt http.user_agent="APN/1.0 HashiCorp/1.0 Terraform/1.4.2 (+https://www.terraform.io) terraform-provider-aws/4.59.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go-v2/1.17.6 os/linux lang/go/1.19.6 md/GOOS/linux md/GOARCH/arm64 api/lambda/1.30.1" tf_mux_provider=*schema.GRPCProviderServer aws.operation=GetFunction http.request.body= http.request.header.authorization="AWS4-HMAC-SHA256 Credential=test/20230321/us-west-1/lambda/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-date, Signature=*****" http.request.header.x_amz_date=20230321T141913Z tf_provider_addr=registry.terraform.io/hashicorp/aws tf_rpc=ApplyResourceChange timestamp=2023-03-21T14:19:13.110Z


If I instead create my own local provider [as solved here](https://stackoverflow.com/questions/74321058/terraform-with-localstack-basic-setup-doesnt-work) it works with regular `terraform`:
```tf
provider "aws" {
  access_key                  = "local"
  secret_key                  = "local"
  skip_region_validation      = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  s3_use_path_style           = true  // not sure if this is necessary..?

  endpoints {
    dynamodb = "http://localstack:4566"
    s3   = "http://localstack:4566"
    iam   = "http://localstack:4566"
    lambda   = "http://localstack:4566"
  }
}


module "aws-lambda" {
  source = "../../../modules/aws-lambda"
  env = "local"
}
```

**Comment by lakkeger** [comment] 2023-10-23 10:33
Hi @evbo!
Thank you for your patience. I was unable to recreate this behaviour in my environment (LS 2.3.2, TF 1.5.7 & tf/aws 5.22.0), so may I ask if this error still persist in your case?
If so, could you please provide which version of Localstack are you running and the log of Localstack when you try to create the bucket?

**Comment by evbo** [comment] 2023-10-23 13:46
I'm not currently using localstack, sorry

**Comment by lakkeger** [comment] 2023-10-23 19:49
Closing the issue as we can't reproduce it.

**Closed by lakkeger** 2023-10-23 19:49 UTC
Labels: wontfix
