### ISSUE TITLE
Can't modify the auto generated localstack_providers_override.tf

### ISSUE THREAD

**Issue by aoi-ue** [localstack/terraform-local#43] opened 2024-01-17 07:50 UTC
Terraform v1.6.6
on darwin_arm64

 Error: Unsupported argument
│
│   on localstack_providers_override.tf line 84, in provider "aws":
│   84: scheduler = "http://localhost:4566"
│
│ An argument named "scheduler" is not expected here.

running `terraform plan` gives no issue, so I believe this wrapper did not handle this scheduler argument. 

On my end, I can't modify the auto generated localstack_providers_override.tf

**Comment by lakkeger** [comment] 2024-01-17 08:42
Hi @aoi-ue!
Thanks for getting in touch with us. Can you please provide a minimal example to reproduce the issue, so we can look into it what might goes wrong there?
As an alternative, you have the option to create further override files which are applied in lexicolographical order, this behaviour is described in Terraform's official documentation [here](https://developer.hashicorp.com/terraform/language/files/override).

**Comment by aoi-ue** [comment] 2024-01-18 11:20
Thanks @lakkeger for the prompt reply. 

https://github.com/rcybersec/terraform-aws-vpc-ec2-s3 could you please try running with this?

**Comment by lakkeger** [comment] 2024-01-22 08:26
Hi @aoi-ue,
I've run the repo's code, the only problem I've found was the image filtering which could be adjusted manually to work properly.
Can you verify that your code uses the latest version of both Localstack and the terraform-local package, please?

**Comment by lakkeger** [comment] 2024-02-18 18:14
Hi @aoi-ue,
Could you please verify if your issue had been resolved in the mean time please?

**Comment by lakkeger** [comment] 2024-06-24 11:00
I'm closing this issue due to inactivity.

**Closed** 2024-06-24 11:01 UTC
Labels: question
